Iter13
developerc/reductorUrl pull request #13
Opened 2024-12-31 17:18 UTC by developerc

Отправляю на проверку

2025-01-04 16:31 UTC, zhark0vv commented
Подними, пожалуйста, версию Go до go 1.22.

2025-01-04 16:51 UTC, zhark0vv requested changes

2025-01-04 16:51 UTC, zhark0vv commented on file_storage2.txt
> +{"uuid":1,"short_url":"1","original_url":"http://blabla.ru"}
Стоит убрать файл из репозитория.

2025-01-04 16:51 UTC, zhark0vv commented on internal/logger/logger.go
>  func Initialize(level string) (*zap.Logger, error) {
Можно принять `zap.Level `и не выводить из строки.

2025-01-04 16:51 UTC, zhark0vv commented on internal/config/config_http_server.go
> +	serverSettings := ServerSettings{}
```
serverSettings := ServerSettings{
TypeStorage: "..."
}
```

2025-01-04 16:51 UTC, zhark0vv commented on internal/config/config_http_server.go
> +	dbStorage := flag.String("d", "host=localhost user=admin password=admin dbname=test sslmode=disable", "address connect to DB")
```
При отсутствии переменной окружения DATABASE_DSN или флага командной строки -d или при их пустых значениях вернитесь последовательно к:
хранению сокращённых URL в файле при наличии соответствующей переменной окружения или флага командной строки;
хранению сокращённых URL в памяти.
```

Тут не должно быть дефолта.

2025-01-04 16:51 UTC, zhark0vv commented on internal/config/config_http_server.go
> +		log.Println("DbStorage from flag:", serverSettings.DBStorage)
Стоит использовать существующий инстанс zap.

2025-01-04 16:51 UTC, zhark0vv commented on internal/config/config_http_server.go
> +	TypeStorage string
Стоит использовать типизированные константы, вместо строк, т.к. по контракту сейчас не понятны возможные варианты.

2025-01-04 16:51 UTC, zhark0vv commented on internal/server/server.go
> +		if errors.As(err, &pgErr) && pgerrcode.IsIntegrityConstraintViolation(pgErr.Code) && pgErr.ConstraintName == "must_be_different" {
Эту логику должен делать сервис, а не сервер. Это часть бизнес-логики.
Стоит,

1. На уровне репозитория обработать pg-ошибку и прокинуть типизированную доменную ошибку выше;
2. Здесь обработать доменную ошибку.

2025-01-04 16:51 UTC, zhark0vv commented on internal/server/server.go
> +			log.Println("Такой оригинальный URL уже существует")
1. Не тот логгер.
2. Русский язык, лучше изменить на английский.

2025-01-04 16:51 UTC, zhark0vv commented on internal/server/server.go
> +		var pgErr *pgconn.PgError
Аналогично комментариям выше.

2025-01-04 16:51 UTC, zhark0vv commented on internal/service/memory/helper_service.go
> +	db, err := sql.Open("pgx", dsn)
Пинг не должен открывать соединение, его должен открывать конструктор и инкапсулировать в структуру сервиса, этот метод только должен выполнять пинг.

2025-01-04 16:51 UTC, zhark0vv commented on internal/service/memory/helper_service.go
> +func createTable(shu *ShortURLAttr) error {
Это миграция. Она должна выполняться отдельно. Посмотри в сторону https://github.com/pressly/goose

2025-01-04 16:51 UTC, zhark0vv commented on internal/service/memory/helper_service.go
> +	const cr string = "CREATE TABLE IF NOT EXISTS url_table( uuid serial primary key, original_url TEXT CONSTRAINT must_be_different UNIQUE)"
Слово `table` в имени таблицы - это лишнее.

2025-01-04 16:51 UTC, zhark0vv commented on internal/service/memory/helper_service.go
> +	row := db.QueryRowContext(ctx, "SELECT uuid FROM url_table WHERE original_url=$1", originalURL)
Репозиторная логика в сервисном слое, стоит добавить отдельный компонент приложения.

2025-01-04 16:51 UTC, zhark0vv commented on internal/service/memory/helper_service.go
> +	db, err := sql.Open("pgx", dsn)
Переоткрытие соединения для каждого запроса. Соединение должно открываться единожды.

2025-01-04 16:51 UTC, zhark0vv commented on internal/server/server.go
> +	val := reflect.ValueOf(s.service)
Не стоит, это очень дорогая операция.
Как я говорил в прошлых ревью, синглтон - антиппатерн.

Передай сервис в структуру сервера, тогда вызовы будут типа таких:
`s.svc.Ping(...)`

2025-01-04 16:51 UTC, zhark0vv commented on internal/server/server.go
> +	var buf bytes.Buffer
Лучше отдать batch-insert на уровень драйвера, это будет быстрее.

pgx умеет в такое из коробки:

```go
func (pg *postgres) BulkInsertUsers(ctx context.Context, users []model.User) error {
  query := `INSERT INTO users (name, email) VALUES (@userName, @userEmail)`

  batch := &pgx.Batch{}
  for _, user := range users {
    args := pgx.NamedArgs{
      "userName": user.Name,
      "userEmail": user.Email,
    }
    batch.Queue(query, args)
  }
  
  results := pg.db.SendBatch(ctx, batch)
  defer results.Close()

  for _, user := range users {
    _, err := results.Exec()
    if err != nil {
      var pgErr *pgconn.PgError
      if errors.As(err, &pgErr) && pgErr.Code == pgerrcode.UniqueViolation {
          log.Printf("user %s already exists", user.Name)
          continue
      }

      return fmt.Errorf("unable to insert row: %w", err)
    }
  }

  return results.Close()
}
```

2025-01-05 15:42 UTC, developerc commented on file_storage2.txt
> +{"uuid":1,"short_url":"1","original_url":"http://blabla.ru"}
Убрал файл

2025-01-05 16:09 UTC, developerc commented on internal/logger/logger.go
>  func Initialize(level string) (*zap.Logger, error) {
Это кусок из моего предыдущего инкремента. В тринадцатом переделал.

2025-01-05 17:06 UTC, developerc commented on internal/config/config_http_server.go
> +	dbStorage := flag.String("d", "host=localhost user=admin password=admin dbname=test sslmode=disable", "address connect to DB")
Убрал дефолтное значение.

2025-01-05 17:44 UTC, developerc commented on internal/config/config_http_server.go
> +		log.Println("DbStorage from flag:", serverSettings.DBStorage)
Переделал логирование на zap

2025-01-05 18:46 UTC, developerc commented on internal/config/config_http_server.go
> +	TypeStorage string
Переделал строки в типизированные константы. Так действительно правильнее.

2025-01-06 12:35 UTC, developerc commented on internal/server/server.go
> +		if errors.As(err, &pgErr) && pgerrcode.IsIntegrityConstraintViolation(pgErr.Code) && pgErr.ConstraintName == "must_be_different" {
переделал

2025-01-06 12:36 UTC, developerc commented on internal/server/server.go
> +			log.Println("Такой оригинальный URL уже существует")
сделал

2025-01-06 12:36 UTC, developerc commented on internal/server/server.go
> +		var pgErr *pgconn.PgError
переделал и для JSON-a

2025-01-06 13:51 UTC, developerc commented on internal/service/memory/helper_service.go
> +	db, err := sql.Open("pgx", dsn)
Да, прочитал что соединение не обязательно открывать, закрывать в каждой функции. Можно открыть один раз и использовать его. Переделал.

2025-01-06 14:11 UTC, developerc commented on internal/service/memory/helper_service.go
> +	const cr string = "CREATE TABLE IF NOT EXISTS url_table( uuid serial primary key, original_url TEXT CONSTRAINT must_be_different UNIQUE)"
исправил

2025-01-06 14:20 UTC, developerc commented on internal/service/memory/helper_service.go
> +func createTable(shu *ShortURLAttr) error {
Я полагаю функции из библиотеки надо применять ради облегчения работы. Увеличивать в размере приложение ради одного создания таблицы не вижу резона.

2025-01-06 14:21 UTC, developerc commented on internal/service/memory/helper_service.go
> +	db, err := sql.Open("pgx", dsn)
исправил

2025-01-06 15:40 UTC, developerc commented on internal/service/memory/helper_service.go
> +	row := db.QueryRowContext(ctx, "SELECT uuid FROM url_table WHERE original_url=$1", originalURL)
getShortByOriginalURL это вспомогательная функция, не является методом сервиса

2025-01-07 14:18 UTC, developerc commented on internal/server/server.go
> +	val := reflect.ValueOf(s.service)
Переделал

2025-01-08 12:01 UTC, developerc commented on internal/server/server.go
> +	var buf bytes.Buffer
Переделал, в случае DBStorage и запроса http://localhost:8080/api/shorten/batch использую pgx.Batch

2025-01-09 10:39 UTC, zhark0vv requested changes

2025-01-09 10:39 UTC, zhark0vv commented on internal/api/api.go
> +		zapLogger, err := logger.Initialize("Info")
Как писал ранее, вывод из строки стоит заменить на передачу уровня.

2025-01-09 10:39 UTC, zhark0vv commented on internal/server/server.go
> +		if _, ok := err.(*memory.ErrorURLExists); ok {
https://pkg.go.dev/errors#As

2025-01-09 10:39 UTC, zhark0vv commented on internal/service/memory/helper_service.go
> +		batch.Queue("insert into url( original_url) values ($1)", longURL.OriginalURL)
Репозиторная логика в сервисном слое, стоит вынести отдельный компонент.

2025-01-09 10:39 UTC, zhark0vv commented on internal/service/memory/helper_service.go
> +func createTable(shu *ShortURLAttr) error {
Ок. Но тогда хотя бы стоит вынести ее из сервисного слоя в отдельный компонент, который запустится при старте приложения.
------
Сделал

2025-01-09 10:39 UTC, zhark0vv commented on internal/service/memory/helper_service.go
> +	row := db.QueryRowContext(ctx, "SELECT uuid FROM url_table WHERE original_url=$1", originalURL)
Функция находится в сервисном пакете и принадлежит ему.
Рекомендую создать entity репозитория и инкапсулировать в нем логику, связанную с БД.
----
Перенес все в db_storage

2025-01-09 10:39 UTC, zhark0vv commented on internal/service/db_storage/db_service.go
> +package dbstorage
Пустой файл.

2025-01-09 10:39 UTC, zhark0vv commented on internal/service/memory/reflect.go
> +func (s *Service) AddLongURL(i int, link string) {
Стоит убрать рефлексию и использовать методы репозитория.

2025-01-09 12:28 UTC, developerc commented on internal/api/api.go
> +		zapLogger, err := logger.Initialize("Info")
Правильное замечание, переделал. Теперь передаю логгер сервера в аргументе функции.

2025-01-09 14:09 UTC, developerc commented on internal/server/server.go
> +		if _, ok := err.(*memory.ErrorURLExists); ok {
Переделал

2025-01-09 19:17 UTC, developerc commented on internal/service/memory/helper_service.go
> +		batch.Queue("insert into url( original_url) values ($1)", longURL.OriginalURL)
Работу с DB вынес в db_storage

2025-01-09 20:08 UTC, developerc commented on internal/service/db_storage/db_service.go
> +package dbstorage
Теперь здесь вся работа с DB

2025-01-10 10:39 UTC, developerc commented on internal/service/memory/reflect.go
> +func (s *Service) AddLongURL(i int, link string) {
Исправил

2025-01-29 16:33 UTC, merged