Iter9
developerc/reductorUrl pull request #9
Opened 2024-12-15 15:40 UTC by developerc

Отправляю на проверку

2024-12-18 09:11 UTC, zhark0vv commented
Функция `GetShortURLAttr()` не используется, ее стоит убрать.

2024-12-19 14:40 UTC, zhark0vv requested changes

2024-12-19 14:40 UTC, zhark0vv commented on internal/config/config-http-server.go
>  var srvSetGlob ServerSettings
Тут стоит убрать глобальные настройки и использовать конкретный инстанс.

2024-12-19 14:40 UTC, zhark0vv commented on internal/config/config-http-server.go
> +		fmt.Println("LogLevel from flag: ", srvSetGlob.LogLevel)
fmt -> log/slog/zap

2024-12-19 14:40 UTC, zhark0vv commented on internal/middleware/gzipMiddleware.go
> +package middleware
Нейминг файлов. Если это два слова, принято использовать snake_case.

2024-12-19 14:40 UTC, zhark0vv commented on internal/middleware/gzipMiddleware.go
> +package middleware
Пересмотри все файлы в проекте, пожалуйста.

2024-12-19 14:40 UTC, zhark0vv commented on internal/server/run.go
> +var service memory.Service
Глобальная переменная. Стоит избегать в пользу локальных инстансов.

2024-12-19 14:40 UTC, zhark0vv commented on internal/logger/logger.go
> +var Log *zap.Logger = zap.NewNop()
Опять же, лучше, если логгер будет не глобальной зависимостью для модулей, которым он явно нужен.

2024-12-19 14:40 UTC, zhark0vv commented on internal/middleware/middleware.go
> +func Middleware(h http.Handler) http.Handler {
Middleware - не самый очевидный нейминг.
Какая Middleware?

То же самое касается имени файла.

2024-12-19 14:40 UTC, zhark0vv commented on internal/server/server.go
> +func (s *Server) GetLongLink(w http.ResponseWriter, r *http.Request) {
Два метода выше - приватный, а этот - публичный. Почему так?

2024-12-19 14:40 UTC, zhark0vv commented on internal/server/server_test.go
> +	t.Run("#1_PostTest", func(t *testing.T) {
`TestGetLink`, но кейсы с постированием.
Стоит разнести тесты, согласно их неймингу.

2024-12-19 14:40 UTC, zhark0vv commented on internal/service/filestorage/filestorage.go
> +var producer Producer
Глобальные переменные.

2024-12-19 14:40 UTC, zhark0vv commented on internal/service/filestorage/filestorage.go
> +func GetProducer() *Producer {
Не стоит, передавай инстанс продюсера туда, где он нужен. В явном виде.

2024-12-19 14:40 UTC, zhark0vv commented on internal/service/filestorage/filestorage.go
> +func (c *Consumer) GetEvents() ([]Event, error) {
Get - это один.
Тут это, скорее, List.

2024-12-19 14:40 UTC, zhark0vv commented on internal/service/memory/inMemoryService.go
> +type Service struct {
Встрой Producer в Service также, как repo.
Тогда это будет частная DI. :)

2024-12-19 19:45 UTC, developerc commented on internal/server/run.go
> +var service memory.Service
В файле in_memory_service.go у структуры Service описан метод
func (s Service) GetLongLink(id string) (string, error) который нужен для получения длинного URL. 
В файле server.go у структуры Server есть метод
func (s *Server) GetLongLink(w http.ResponseWriter, r *http.Request) где получаю длинный URL
longURL, err := GetService().GetLongLink(id)
Вообще-то локально у Server должен быть Service у которого можно взять метод GetLongLink(id), но это никак у меня не получилось. Только в run.go объявил переменную service и для нее геттер. Переменная service это ведь не глобальная переменная раз с маленькой буквы?

2024-12-19 19:47 UTC, developerc commented on internal/logger/logger.go
> +var Log *zap.Logger = zap.NewNop()
Исправил на log с маленькой буквы, добавил геттер

2024-12-19 19:47 UTC, developerc commented on internal/config/config-http-server.go
>  var srvSetGlob ServerSettings
Исправил

2024-12-19 19:49 UTC, developerc commented on internal/config/config-http-server.go
> +		fmt.Println("LogLevel from flag: ", srvSetGlob.LogLevel)
Исправил на log. Zap в этом месте еще не создан.

2024-12-19 19:49 UTC, developerc commented on internal/middleware/gzipMiddleware.go
> +package middleware
Исправил все имена файлов на snake_case

2024-12-20 06:17 UTC, zhark0vv commented on internal/server/run.go
> +var service memory.Service
Смотри, ты используешь Singleton, у тебя есть приватный сервис и геттер, отдающий его.
Но в Go это антипаттерн. И причин этому две:

- существование концепции поинтеров
- duck-typing

В Go очень хорошо реализуется классический DI, а отсутствие новых объектов гарантируется поинтерами. Ниже, где ты встроил репозиторий в сервис, ты использовал DI. 

Здесь, вместо геттера, стоит сделать просто конструктор, создать объекь в main-пакете и инжетировать его туда, где он нужен.

Аналогично и для логгера.

2024-12-20 06:34 UTC, developerc commented on internal/server/run.go
> +var service memory.Service
Да, придумал. В in_memory_service.go объявил переменную 
var service interface{}
И в функции 
func NewInMemoryService() Service
сразу проверяю service != nil Если nil, создаю его, если не nil возвращаю service приведенную к Service.

2024-12-20 07:03 UTC, developerc commented on internal/server/server_test.go
> +	t.Run("#1_PostTest", func(t *testing.T) {
Разнес тесты по разным функциям

2024-12-20 07:28 UTC, developerc commented on internal/service/filestorage/filestorage.go
> +func (c *Consumer) GetEvents() ([]Event, error) {
Исправил

2024-12-20 07:50 UTC, zhark0vv commented on internal/server/run.go
> +var service memory.Service
var service interface{} тоже лишнее. 
Возвращай поинтер, когда их создавать пусть решит потребитель.

2024-12-20 08:30 UTC, developerc commented on internal/server/run.go
> +var service memory.Service
Да, можно проверять на nil значение service.repo  Переделал, возвращаю указатель на Service

2024-12-20 11:07 UTC, developerc commented on internal/service/memory/inMemoryService.go
> +type Service struct {
Producer и Consumer переделал в DI

2024-12-20 11:07 UTC, developerc commented on internal/service/filestorage/filestorage.go
> +func GetProducer() *Producer {
Сделал

2024-12-20 11:07 UTC, developerc commented on internal/service/filestorage/filestorage.go
> +var producer Producer
переделал в DI

2024-12-20 15:38 UTC, zhark0vv requested changes

2024-12-20 15:38 UTC, zhark0vv commented on internal/config/config_http_server.go
> +	srvSetGlob := ServerSettings{}
`srvSetGlob` уже не `Glob`.

2024-12-20 15:38 UTC, zhark0vv commented on internal/config/config_http_server.go
> +	srvSetGlob := ServerSettings{}
`new(...)`

2024-12-20 15:38 UTC, zhark0vv commented on internal/middleware/middleware.go
> +func Middleware(h http.Handler) http.Handler {
Тут не исправлено.

2024-12-20 15:38 UTC, zhark0vv commented on internal/logger/logger.go
> +var zapLog *zap.Logger = zap.NewNop()
Тут тоже лучше DI применить.

2024-12-20 15:38 UTC, zhark0vv commented on internal/server/server.go
> +func (s *Server) GetLongLink(w http.ResponseWriter, r *http.Request) {
Тут тоже не исправлено.

2024-12-20 15:38 UTC, zhark0vv commented on internal/server/server.go
> +	log.Println("id: ", chi.URLParam(r, "id"))
Где-то zap, где-то log. Стоит унифицировать.

2024-12-20 15:38 UTC, zhark0vv commented on internal/server/run.go
> +var server Server
И тут тоже лучше DI.

2024-12-20 15:45 UTC, zhark0vv requested changes

2024-12-20 15:45 UTC, zhark0vv commented on internal/config/config_http_server.go
> +	if !ok || val == "" {
LookupEnv -> Getenv, ты и так строку проверяешь, булевый флаг только усложняет эту ветку.

2024-12-20 17:01 UTC, developerc commented on internal/config/config_http_server.go
> +	srvSetGlob := ServerSettings{}
Переименовал в srvSet

2024-12-20 17:06 UTC, developerc commented on internal/config/config_http_server.go
> +	srvSetGlob := ServerSettings{}
Что сделать? Переименовать NewServerSettings() в new() ?

2024-12-20 17:31 UTC, developerc commented on internal/config/config_http_server.go
> +	if !ok || val == "" {
Оставить так?
if val == "" {

2024-12-20 18:22 UTC, developerc commented on internal/logger/logger.go
> +var zapLog *zap.Logger = zap.NewNop()
ZapLog переделал на DI.
Middleware что исправлять?

2024-12-20 18:25 UTC, developerc commented on internal/server/server.go
> +	log.Println("id: ", chi.URLParam(r, "id"))
Распечатывалась отладочная информация, убрал.

2024-12-20 18:38 UTC, developerc commented on internal/server/run.go
> +var server Server
Сделал DI

2024-12-21 06:41 UTC, zhark0vv commented
Подсвечиваю исправления на вырост, которые я озвучивал на сессии 1:1.

1. Не использовать глобальные состояния структур. Если что-то создается, его инициализирует и возвращает конструктор, никаких глобальных переменных на пакет.
2. Никаких хаков с конвертацией интерфейсов в структуру реализации, это очень дорогая операция.

Если работаем с абстракцией, то честно выносим методы, которые позволяют работать с абстракцией.
При этом ее внутренние атрибуты обязаны оставаться приватными.

См. референс в архиве в Пачке.

2024-12-25 13:05 UTC, developerc commented
Сделал пункт 2. Вместо Type Assertion использую reflect.

2024-12-26 18:44 UTC, merged